apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctse
  name: ctse
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ctse
status:
  loadBalancer: {}